name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ffmpeg
        go install golang.org/x/tools/cmd/deadcode@latest
    - name: deadcode
      run: |
        DEAD=$(deadcode ./example/webserver)
        if [ -n "$DEAD" ]; then
          echo "deadcode found the following unused code:"
          echo "$DEAD"
          exit 1
        fi
    - name: Install doom wad
      run: wget https://github.com/Akbar30Bill/DOOM_wads/raw/refs/heads/master/doom1.wad
    - name: test
      run: ./run_tests.sh
