name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ffmpeg
        go install golang.org/x/tools/cmd/deadcode@latest
    - id: deadcode
      run: |
        deadcode ./example/webserver
    - name: deadcode check
      run: |
        if [ -n "${{join(steps.deadcode.outputs.*, '\n')}}" ] ; then echo "Dead code found"; exit 1; fi
    - name: Install doom wad
      run: wget https://github.com/Akbar30Bill/DOOM_wads/raw/refs/heads/master/doom1.wad
    - name: test
      run: ./run_tests.sh
